#ifndef CLTINYENGINELIB_GLOBAL_H
#define CLTINYENGINELIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CLTINYENGINELIB_LIBRARY)
#  define CLTINYENGINELIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CLTINYENGINELIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CLTINYENGINELIB_GLOBAL_H
